GestaoFinanceira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')), #Inclui a pagina inicial nos caminhos
    path('auth/', include('apps.usuarios.urls')), #Chamando as urls do aplicativo usuarios
]

apps/core/urls.py
from django.urls import path, include
from apps.core import views
from apps.financeiro.views import menuExtrato

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transacoes/', include('apps.financeiro.urls')),
    path('objetivos/', include('apps.objetivos.urls')),
    path('meta/', include('apps.metas.urls')),
    path('extrato/<int:mes>/<int:ano>/', menuExtrato, name='menuExtrato'),
    path('relatorio/', include('apps.relatorio.urls'), name='relatorio'),
    path('notfound/', views.notfound, name='erro404'),
    path('erro/<str:mensagem>', views.erro, name='erro')
]

apps/usuarios/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views # Importei essa biblioteca para utilizar as views do Django de auth
from . import views

app_name = 'usuario'

# As URLs de Login e Cadastro
urlpatterns = [
    path('cadastro/', views.cadastrar, name='cadastro'),
    path('login/', views.logar, name='login'),
    path('logout/', views.deslogar, name='logout'),
    path('configuracoes/', views.configuraçoes, name='configuracoes'),
    #Foi preciso colocar o success_url devido que o Django não estava encontrando as URLs para redirecionar automaticamente
    path('resetar-senha/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('usuario:password_reset_done')), name='password_reset'),
    path('resetar-senha/enviado/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('resetar-senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('usuario:password_reset_complete')), name='password_reset_confirm'),
    path('resetar-senha/concluido/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/core/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from apps.financeiro.models import Categoria, ParcelasTransacao
from apps.financeiro.operacoes.getter import GetterFinanceiro
from apps.financeiro.operacoes.saldo import Historico
from apps.financeiro.operacoes.transacao import OperacoesTransacao
from apps.objetivos.models import Objetivos
from apps.metas.models import Metas
from apps.metas.operacoes.metas import OperacoesMeta
from common.dominio.data import Data

from datetime import date

def index(request):
    return render(request, 'index.html')

def dashboard(request):
    if not request.user.is_authenticated:
        return redirect(reverse('core:index'))
    if not request.method == "GET":
        return redirect(reverse('core:dashboard'))

    user = request.user.id

    metas_ativas = Metas.objects.filter(user_fk__id=user)
    operacoes = OperacoesMeta(user)
    for meta in metas_ativas:
        operacoes.atualizarStatusMeta(meta)
    
    historico = Historico(user)

    operacoes_transacao = OperacoesTransacao(user)
    operacoes_transacao.verificarParcelasPagas()

    historico.verificarInsercoesHistorico()
    infos_financeiro = GetterFinanceiro(user)

    saldo_atual = infos_financeiro.saldoAtual()
    hoje = date.today()

    ganhos_mes = infos_financeiro.receitaTotalMes(hoje.month, hoje.year)
    gastos_mes = infos_financeiro.despesaTotalMes(hoje.month, hoje.year)

    dicionario_despesas_categorias = infos_financeiro.valorTotalDasCategorias(hoje.month, hoje.year, 'despesa')
    dicionario_receitas_categorias = infos_financeiro.valorTotalDasCategorias(hoje.month, hoje.year, 'receita')

    categorias = Categoria.objects.all()

    objetivo_prox = Objetivos.objects.filter(user_fk=user, status="A").order_by('valor_guardado').first()
    meta_prox = Metas.objects.filter(user_fk=user, status="A").order_by('data_fim').first()

    informacoes_dashboard = {'saldo_atual': saldo_atual
                            , 'username': request.user.username
                            , 'ganhos_mes': ganhos_mes
                            , 'gastos_mes': gastos_mes
                            , 'balanco_mes': ganhos_mes - gastos_mes
                            , 'mes_ano': Data.formatarMesAno(hoje.month, hoje.year)
                            , 'lancamentos_futuros': infos_financeiro.proximasTresParcelas()
                            , 'ultimos_lancamentos': infos_financeiro.ultimaCincoParcelas()
                            , 'categorias': categorias
                            , 'todas_categorias_receita': categorias.filter(tipo='R')
                            , 'todas_categorias_despesa': categorias.filter(tipo='D')
                            , 'lista_receitas_categoria': ','.join(dicionario_receitas_categorias.values())
                            , 'categorias_transacoes_receitas': ','.join(dicionario_receitas_categorias.keys())
                            , 'lista_despesas_categoria': ','.join(dicionario_despesas_categorias.values())
                            , 'categorias_transacoes_despesas': ','.join(dicionario_despesas_categorias.keys())
                            , 'mes': hoje.month
                            , 'ano': hoje.year
                            , 'meta': meta_prox
                            , 'objetivo': objetivo_prox
                            , 'hoje': date.today()
    }
    return render(request, 'dashboard.html', informacoes_dashboard)

def notfound(request):
    if not request.user.is_authenticated:
        return redirect(reverse('core:index'))
    return render(request, 'erro/404.html')

def erro(request, mensagem):
    if not request.user.is_authenticated:
        return redirect(reverse('core:index'))
    return render(request, 'erro/erroinesperado.html', {'mensagem': mensagem})

apps/core/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>U-Balance</title>
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}"/>
</head>
<body>
<header>
    <div class="container">
        <div class="logo">U-Balance</div>
        <nav>
            {% if not user.is_authenticated %}
            <a href="{% url 'usuario:login' %}">Entrar</a>
            <a href="{% url 'usuario:cadastro' %}">Cadastrar</a>
            {% else %}
            <a href="{% url 'core:dashboard' %}">Acessar dashboard</a>
            <a href="{% url 'usuario:logout' %}">Logout</a>
            {% endif %}
        </nav>
    </div>
</header>

<section class="hero">
    <h1>Controle total da sua vida financeira</h1>
    <p>Organize, planeje e alcance seus objetivos com inteligência.<br><br>Vamos começar criando uma conta, é só clicar
        no botão abaixo!</p>
    <a href="{% url 'usuario:cadastro' %}">
        <button>Comece agora</button>
    </a>
</section>

<section class="servicos">
    <h2>Nossos Serviços</h2>
    <div class="cards">
        <div class="card">
            <h3>Crie metas</h3>
            <p>Gerencie as suas metas financeira, sabendo exatamente o qual valor atingir.
                <br>Com acompanhamento direto com as transações </p>
        </div>
        <div class="card">
            <h3>Organização de Gastos</h3>
            <p>Saiba exatamente para onde vai seu dinheiro e como economizar mais.</p>
        </div>
        <div class="card">
            <h3>Defina Objetivos</h3>
            <p>Esta planejando juntar dinheiro para realizar aquele sonho?<br>Defina objetivos e tenha um fácil acompanhamento dos valores guardados para atingir o seu sonho!</p>
        </div>
    </div>
</section>

<section class="cta">
    <h2>Está com dúvidas ou com problemas na plataforma?</h2>
    <button onclick="alert('Apenas pra exemplo')">Fale Conosco</button>
</section>

<footer>
    <p>&copy; 2025 - U-Balance</p>
</footer>
</body>
</html>