GestaoFinanceira/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')), #Inclui a pagina inicial nos caminhos
    path('auth/', include('apps.usuarios.urls')), #Chamando as urls do aplicativo usuarios
]

apps/core/urls.py
from django.urls import path, include
from apps.core import views
from apps.financeiro.views import menuExtrato

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('transacoes/', include('apps.financeiro.urls')),
    path('objetivos/', include('apps.objetivos.urls')),
    path('meta/', include('apps.metas.urls')),
    path('extrato/<int:mes>/<int:ano>/', menuExtrato, name='menuExtrato'),
    path('relatorio/', include('apps.relatorio.urls'), name='relatorio'),
    path('notfound/', views.notfound, name='erro404'),
    path('erro/<str:mensagem>', views.erro, name='erro')
]

apps/usuarios/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views # Importei essa biblioteca para utilizar as views do Django de auth
from . import views

app_name = 'usuario'

# As URLs de Login e Cadastro
urlpatterns = [
    path('cadastro/', views.cadastrar, name='cadastro'),
    path('login/', views.logar, name='login'),
    path('logout/', views.deslogar, name='logout'),
    path('configuracoes/', views.configuraçoes, name='configuracoes'),
    #Foi preciso colocar o success_url devido que o Django não estava encontrando as URLs para redirecionar automaticamente
    path('resetar-senha/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('usuario:password_reset_done')), name='password_reset'),
    path('resetar-senha/enviado/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('resetar-senha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('usuario:password_reset_complete')), name='password_reset_confirm'),
    path('resetar-senha/concluido/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

apps/usuarios/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models

from decimal import Decimal

class CustomUserManager(UserManager):
    def create_user(self, username, email=None, password=None, **extra_fields):
        if not username:
            raise ValueError("O username deve ser preenchido")
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)  # só chama save 1 vez
        return user

    def create_superuser(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superusuário precisa ter is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superusuário precisa ter is_superuser=True.')
        return self.create_user(username, email, password, **extra_fields)


class CustomUser(AbstractUser):
    objects = CustomUserManager()
    saldoAtual = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    dataUltimaTransacaoVerificada = models.DateField(default=date.today())

    def operarSaldoAtual(self, valor:Decimal, tipo:str, inversor:bool = False):
        valor = abs(valor)
        if inversor == True:
            valor = -valor
        if tipo == 'R':
            self.saldoAtual += valor
        elif tipo == 'D':
            self.saldoAtual -= valor
        self.save()

    def __str__(self):
        return f'''
        {str(self.id)} - {self.username} - {self.email} - {str(self.saldoAtual)}
        '''

apps/usuarios/views.py
from datetime import date
from idlelib.rpc import request_queue

from django.db.models import Q
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.template.smartif import Literal

from apps.financeiro.models import Categoria
from django.urls import reverse
from datetime import date

from apps.financeiro.models import HistoricoSaldo

from apps.usuarios.models import CustomUser

#Função para cadastrar novos usuarios
def cadastrar(request):
    #Caso o usuario já esteja logado vai ser redirecionado para a página principal
    if request.user.is_authenticated:
        return redirect(reverse('core:index'))
    
    if request.method == "GET":
        return render(request, 'cadastro.html')
    else:
        # Armazenando as informações fornecidas para a criação do usuario
        usuario = request.POST.get('usuario', '').strip()
        email = request.POST.get('email', '').strip()
        senha = request.POST.get('senha', '').strip()
        repetir_senha = request.POST.get('repetir_senha', '').strip()
        
        # Confirmação de senha
        if senha != repetir_senha:
            messages.error(request, 'As senhas não coincidem. Tente novamente.')
            return redirect(reverse('usuario:cadastro'))
        
        # Filtra se já existe um e-mail ou usuario parecidos no banco de dados, para evitar cadastros repetidos.
        user = CustomUser.objects.filter(Q(username=usuario) | Q(email=email)).first()
        if user:
            messages.error(request, 'Já existe um usuário com esse nome de usuário ou email')
            return redirect(reverse('usuario:cadastro'))
        
        # Chamando a função de criar usuário do Django
        user = CustomUser.objects.create_user(username=usuario, email=email, password=senha)

        #Logando o usuario automaticamente e redicionando para a aplicação
        login(request, user)
        HistoricoSaldo.inicializarPrimeiroValor(user)
        return redirect(reverse('core:dashboard'))

#Função de Login
def logar(request):
    if request.user.is_authenticated:
        return redirect(reverse('core:dashboard'))
        
    if request.method == "GET":
        return render(request, 'login.html')

    # Váriaveis que vão receber os dados do frontend
    usuario = request.POST.get('usuario', '').strip()
    senha = request.POST.get('senha','').strip()

    # Autentica se o email e a senha são compativeís
    user = authenticate(request, username=usuario, password=senha)

    # Caso as informações estejam certezas ele loga
    if user:
        login(request, user)
        return redirect(reverse('core:dashboard'))
    else:  # Se não informa erro devido que retornou nenhum objeto
        messages.error(request, 'Usuário ou senha errada')
        return redirect(reverse('usuario:login'))

def deslogar(request):
    logout(request)
    return redirect(reverse('core:index'))

def configuraçoes(request):
    user = request.user

    if not user.is_authenticated:
        return redirect(reverse('core:index'))

    categorias = Categoria.objects.all()
    context = {
        'mes': date.today().month
        , 'ano': date.today().year
        , 'usuario': user
        , 'categorias': categorias
        , 'todas_categorias_receita': categorias.filter(tipo='R')
        , 'todas_categorias_despesa': categorias.filter(tipo='D')
        , 'hoje': date.today()
    }

    if not request.method == "POST":
        return render(request, 'configuraçoes.html', context)

    if "atualizar_perfil" in request.POST:
        novo_usuario = request.POST.get('nome_usuario', '').strip()
        novo_email = request.POST.get('email', '').strip()

        if not novo_usuario or not novo_email:
            messages.error(request, "Nome de usuário e e-mail são obrigatórios")
            return redirect(reverse('usuario:configuracoes'))

        pode_salvar = True

        if user.username != novo_usuario:
            if CustomUser.objects.filter(username__exact=novo_usuario).exists():
                messages.error(request, f"O nome de usuário '{novo_usuario}' já está em uso")
                pode_salvar = False

        if user.email != novo_email:
            if CustomUser.objects.filter(email__exact=novo_email).exists():
                messages.error(request, f"O e-mail '{novo_email}' já está em uso")
                pode_salvar = False

        if pode_salvar:
            user.username = novo_usuario
            user.email = novo_email
            user.save()
            messages.success(request, "Suas informações foram atualizadas com sucesso")
            return render(request, 'configuraçoes.html', context)

        return redirect(reverse('usuario:configuracoes'))

    elif "confirmar_senha" in request.POST:
        senha_atual = request.POST.get('senha_atual', '').strip()
        nova_senha = request.POST.get('nova_senha', '').strip()
        confirmar_senha = request.POST.get('confirmar_senha', '').strip()

        if not user.check_password(senha_atual):
            messages.error(request, "A senha atual está incorreta.")
            return redirect(reverse('usuario:configuracoes'))

        if not nova_senha or not confirmar_senha:
            messages.error(request, "Todos os campos de senha são obrigatórios.")
            return redirect(reverse('usuario:configuracoes'))

        if nova_senha != confirmar_senha:
            messages.error(request, "As novas senhas não coincidem.")
            return redirect(reverse('usuario:configuracoes'))

        else:
            user.set_password(nova_senha)
            user.save()
            update_session_auth_hash(request, user)
            messages.success(request, "Senha alterada com sucesso")
            return redirect(reverse('usuario:configuracoes'))

    elif "deletar_conta" in request.POST:
        deslogar(request)
        user.delete()
        # Mensagem que a conta foi deletada com sucesso
        return redirect(reverse('core:index'))

apps/usuarios/templates/cadastro.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro - U-Balance</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'usuarios/css/style-login-cadastro.css' %}">
</head>
<body>
<header>
    <div class="logo"><a href="{% url 'core:index' %}">U-Balance</a></div>
</header>

<main class="form-container">
    <form class="form-box" action="{% url 'usuario:cadastro' %}" method="POST">
        {% csrf_token %}
        <h2>Cadastro</h2>

        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}

        <label for="login">Login</label>
        <input type="text" id="login" name="usuario" required>

        <label for="email">E-mail</label>
        <input type="email" id="email" name="email" required>

        <label for="senha">Senha</label>
        <input type="password" id="senha" name="senha" required>

        <label for="confirmar">Repetir senha</label>
        <input type="password" id="confirmar" name="repetir_senha" required>

        <button type="submit">Cadastrar</button>
        <p class="link">Já tem uma conta? <a href="{% url 'usuario:login' %}">Entrar</a></p>
    </form>
</main>

<footer>
    <p>&copy; 2025 - U-Balance</p>
</footer>
<script>

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    document.addEventListener("DOMContentLoaded", () => {

        sleep(5000).then(() => {
            document.querySelectorAll(".alert").forEach(mensagem => {
                mensagem.style.display = "none"
            });
        });
    })
</script>

</body>
</html>

apps/usuarios/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login - U-Balance</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'usuarios/css/style-login-cadastro.css' %}">
</head>
<body>
<header>
    <div class="logo"><a href="{% url 'core:index' %}">U-Balance</a></div>
</header>
<main class="form-container">
    <form class="form-box" method="POST">
        {% csrf_token %}
        <h2>Login</h2>

        {% if messages %}
            {% for message in messages %}
                <div id="mensagem" class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <script src="{% static 'usuarios/js/mensagem_erro.js' %}"></script>

        <label for="login">Login</label>
        <input type="text" id="login" name="usuario" required>

        <label for="senha">Senha</label>
        <input type="password" id="senha" name="senha" required>

        <button type="submit" href="{% url 'usuario:login' %}">Entrar</button>

        <p class="link"><a href="{% url 'usuario:password_reset' %}">Esqueci minha senha</a></p>
        <p class="link">Não tem uma conta? <a href="{% url 'usuario:cadastro' %}">Cadastre-se</a></p>
    </form>
</main>

<footer>
    <p>&copy; 2025 - U-Balance</p>
</footer>
<script>

    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    document.addEventListener("DOMContentLoaded", () => {

        sleep(5000).then(() => {
            document.querySelectorAll(".alert").forEach(mensagem => {
                mensagem.style.display = "none"
            });
        });
    })
</script>

</body>
</html>